# Generated by Django 2.2 on 2020-06-28 08:42

import accounting.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=40, null=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('username', models.CharField(max_length=100, null=True, unique=True)),
                ('token_id', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2020, 6, 28, 14, 12, 30, 57582))),
            ],
        ),
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_name', models.CharField(max_length=30)),
                ('add_on', models.DateTimeField(default=datetime.datetime(2020, 6, 28, 14, 12, 30, 62594))),
                ('ca_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(default=None, max_length=30)),
                ('add_on', models.DateTimeField(default=datetime.datetime(2020, 6, 28, 14, 12, 30, 61591))),
                ('g_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createid', models.CharField(max_length=100)),
                ('session_id', models.CharField(max_length=300)),
                ('session_key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.DateTimeField(default=datetime.datetime(2020, 6, 28, 14, 12, 30, 63597))),
                ('To', models.DateTimeField(default=datetime.datetime(2020, 6, 28, 14, 12, 30, 63597))),
                ('messagesent', models.IntegerField(default=0)),
                ('contacts_created', models.IntegerField(default=0)),
                ('groups_created', models.IntegerField(default=0)),
                ('campaigns_created', models.IntegerField(default=0)),
                ('templated_created', models.IntegerField(default=0)),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Groupdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.IntegerField(default=0)),
                ('gd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Group')),
            ],
        ),
        migrations.CreateModel(
            name='EmailAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_provider', models.CharField(max_length=50)),
                ('e_email', models.EmailField(max_length=254)),
                ('e_password', models.CharField(max_length=200)),
                ('addon', models.DateTimeField(default=datetime.datetime(2020, 6, 28, 14, 12, 30, 59586))),
                ('addpassword', models.BooleanField(default=False)),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
            ],
        ),
        migrations.CreateModel(
            name='ContactlistFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 6, 28, 14, 12, 30, 60589))),
                ('myfile', models.FileField(upload_to=accounting.models.user_directory_path)),
                ('cf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Contactlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
                ('c_first_name', models.CharField(default=None, max_length=50)),
                ('c_middle_name', models.CharField(default=None, max_length=50)),
                ('c_last_name', models.CharField(default=None, max_length=50)),
                ('c_gender', models.CharField(default=None, max_length=40)),
                ('c_group', models.CharField(default=None, max_length=50)),
                ('c_subgroup', models.CharField(default=None, max_length=50)),
                ('c_status', models.CharField(default=None, max_length=50)),
                ('c_company', models.CharField(default=None, max_length=50)),
                ('c_designation', models.CharField(default=None, max_length=50)),
                ('c_title', models.CharField(default=None, max_length=50)),
                ('c_department', models.CharField(default=None, max_length=50)),
                ('c_university', models.CharField(default=None, max_length=50)),
                ('c_degree', models.CharField(default=None, max_length=50)),
                ('c_passingyear', models.CharField(default=None, max_length=50)),
                ('c_college', models.CharField(default=None, max_length=50)),
                ('c_ctc', models.CharField(default=None, max_length=50)),
                ('c_email', models.EmailField(max_length=254)),
                ('c_alternativeemailid', models.EmailField(default=None, max_length=254)),
                ('c_phone', models.CharField(default=None, max_length=40)),
                ('c_alternativephone', models.CharField(default=None, max_length=40)),
                ('c_city', models.CharField(default=None, max_length=50)),
                ('c_address', models.CharField(default=None, max_length=50)),
                ('c_state', models.CharField(default=None, max_length=50)),
                ('c_country', models.CharField(default=None, max_length=50)),
                ('c_zip', models.CharField(default=None, max_length=50)),
                ('c_industry', models.CharField(default=None, max_length=50)),
                ('c_keyskills', models.CharField(default=None, max_length=50)),
                ('c_totalexperience', models.CharField(default=None, max_length=50)),
                ('c_yearbusiness', models.CharField(default=None, max_length=50)),
                ('c_turnover', models.CharField(default=None, max_length=50)),
                ('c_dateofincorportaion', models.CharField(default=None, max_length=50)),
                ('c_employess', models.CharField(default=None, max_length=50)),
                ('c_addon', models.DateTimeField(default=datetime.datetime(2020, 6, 28, 14, 12, 30, 60589))),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Campaignsdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.IntegerField(default=0)),
                ('cd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Campaigns')),
            ],
        ),
        migrations.CreateModel(
            name='Accountdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, null=True)),
                ('potp', models.CharField(max_length=200, null=True)),
                ('rotp', models.CharField(max_length=200, null=True)),
                ('date2', models.DateTimeField(default=datetime.datetime(2020, 6, 28, 14, 12, 30, 58584))),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 6, 28, 14, 12, 30, 58584))),
                ('defaultaccount', models.EmailField(max_length=254, null=True)),
                ('profile', models.ImageField(null=True, upload_to=accounting.models.user_photo_path)),
                ('everify', models.BooleanField(default=False)),
                ('comlpeted', models.BooleanField(default=False)),
                ('acc_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account')),
            ],
        ),
    ]
